### ISSUE TITLE
Add support for Laravel Scout 10

### ISSUE THREAD

**Issue by kichetof** [Sti3bas/laravel-scout-array-driver#13]
Hi!
Thanks for your great plugin that help me a lot in local :)

Could you add support for Laravel [Scout 10](https://github.com/laravel/scout/releases/tag/v10.0.0) that was just launched?

Thanks a lot!

**Comment by Sti3bas** [comment]
Hey!

[v3.4](https://github.com/Sti3bas/laravel-scout-array-driver/releases/tag/v3.4) was just released.

**Comment by kichetof** [comment]
Hi!
Thanks for the release! Maybe add support for both Scout 9 and 10 ?

**Comment by Sti3bas** [comment]
@kichetof you can use [v3.3](https://github.com/Sti3bas/laravel-scout-array-driver/releases/tag/v3.3) for Scout 9.
